[server]
enable_snappy = false
xbox_auth = false
validate_encryption = true
force_gamemode = false

[game]
name = "UndefinedRedstore Server"
motd = "UndefinedRedstore Server"
max_player = 20
gamemode = "survival"
ipv4_port = 19132
ipv6_port = 19132

[experimental_gameplay]
data_driven_items = true
data_driven_biomes = true
upcoming_creator_features = true
gametest = true
experimental_molang_features = true
cameras = true