[package]
name = "undefined_redstone_nbt"
version = "0.1.0"
edition = "2021"

[dependencies]
binary-util = { path = "../binary_util" }
anyhow = "1.0.86"
flate2 = "1.0.30"
bytes = "1.6.1"
serde = "1.0"
serde_json = "1.0.120"